### ISSUE TITLE
Drop Common.add_directory and replace with  xbmcplugin.addDirectoryItem

### ISSUE THREAD

**Issue by Lunatixz** [moneymaker365/plugin.video.ustvvod#42] opened 2015-02-10 16:58 UTC
This plugin doesn't return proper directory structures via json... You are using a very old method that was written for eden. Please consider updating the core code... Common.add_directory adds a lot of unneeded references, that can be set via properties?

**Comment by slices81** [comment] 2015-02-10 17:19
Duplicate of issue 23, but this one is more detailed.

I really don't want to get rid of common code and make this less maintable. If needed we'll rewrite common.add directory, and not going to solve any thing if we duplicate the same issue 42 times.

It calls xbmcPlugin.addDirectory,  so is it passing mode sitemode etc that is causing the problem.

**Comment by slices81** [comment] 2015-02-10 17:19
Duplicate of issue 23, but this one is more detailed.

I really don't want to get rid of common code and make this less maintable. If needed we'll rewrite common.add directory, and not going to solve any thing if we duplicate the same issue 42 times.

It calls xbmcPlugin.addDirectory,  so is it passing mode sitemode etc that is causing the problem.

**Comment by Lunatixz** [comment] 2015-02-10 18:08
Sorry about the dup... forgot I posted it ;)

I understand it already uses xbmcPlugin.addDirectory... what I meant was a more direct method, clean use of the addDirectory... Since your function adds a lot of references that may not be needed...

Looks like we are on the same page understanding the issue, I hope you can resolve it...
Many of your users want to integrate your feeds through my plugin... but cannot.

Thanks

**Comment by slices81** [comment] 2015-02-10 19:15
If I'm understanding this correctly the issue is around the way args are pass via the URL into  common.arts. The problem is most if not all are used, not sure about thumb but the rest are.

Can you suggest a better way of passing them?

**Comment by Lunatixz** [comment] 2015-02-10 19:57
Here is a modern way to build a itemlist, using properties... you would set your artwork as item properties, you also need to make sure you use setresolver to handle the arguments...

https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/default.py#L860-L864
https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/default.py#L344

**Comment by slices81** [comment] 2015-02-10 20:56
Ok I'm being really slow here. Is it just fanart that is causing you a problem, otherwise can we not get hung up on it it's just another parameter. The code does set properties to set the fanart  but passes it as a parameter so child items an use it. How can I get the properties when I don't have access to the list item.

Already using setresolvedurl on playback, how would it help on a directory?

**Comment by Lunatixz** [comment] 2015-02-11 00:31
When I get some free time i'll make the changes and submit...

**Closed** 2016-04-07 12:24 UTC
